export default {
  // notification
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_NOTIFICATIONS_UNREAD: 'GET_NOTIFICATIONS_UNREAD',

  // user
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  GET_CARDS: 'GET_CARDS',

  // roles
  GET_ROLES: 'GET_ROLES',

  // weapons
  GET_WEAPONS: 'GET_WEAPONS',

  // onesignal
  GET_PLAYER_ID: 'GET_PLAYER_ID',
  GET_PUSH_TOKEN: 'GET_PUSH_TOKEN',

  // chatroom
  GET_CHAT_ROOMS: 'GET_CHAT_ROOMS',

  // Matches
  GET_MATCHES: 'GET_MATCHES',

  // History Message
  GET_HISTORY_MESSAGE: 'GET_HISTORY_MESSAGE'
};
